[tool.poetry]
name = "cooki_fastapi"
version = "0.1.0"
description = "FastAPI template project from Tobi-De"
authors = ["morten.larsen@7sense.no"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.85.0"
uvicorn = "^0.18.3"
pydantic = {extras = ["email", "dotenv"], version = "^1.10.2"}
fastapi-users = "^10.1.5"
tortoise-orm = {extras = ["asyncpg"], version = "^0.19.2"}
fastapi-users-tortoise = "^0.2.0"
aerich = "^0.7.1"
arq = "^0.24.0"
aiosmtplib = "^1.1.6"
python-multipart = "^0.0.5"
rich = "^12.6.0"
typer = "^0.4.2"
watchgod = "^0.8.2"
Jinja2 = "^3.1.2"
httpx = "^0.23.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
factory-boy = "^3.2.1"
pre-commit = "^2.20.0"
mypy = "^0.982"
isort = "^5.10.1"
flake8 = "^5.0.4"
poetryup = "^0.12.3"
ipython = "^8.5.0"
aiosmtpd = "^1.4.2"

[tool.aerich]
tortoise_orm = "app.db.config.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[tool.isort]
profile = "black"

[tool.mypy]
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
